# Generated by Django 2.1.7 on 2019-03-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('dataHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='palestra',
            name='palestrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestras', to='app.Palestrante'),
        ),
    ]
