# Generated by Django 2.1.7 on 2019-03-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palestrante',
            old_name='name',
            new_name='nome',
        ),
    ]
