# Generated by Django 2.0.13 on 2019-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190310_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palestra',
            name='dataHora',
            field=models.DateField(),
        ),
    ]
