# Generated by Django 2.0.13 on 2019-03-12 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190312_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palestra',
            old_name='dataHora',
            new_name='data',
        ),
        migrations.AddField(
            model_name='palestra',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
